# Tests at Travis CI.

language: go

go:
 - 1.3

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y cpio realpath squashfs-tools

install:
 - go get code.google.com/p/go-uuid/uuid
 - go get github.com/jmcvetta/randutil
 - go get github.com/lib/pq
 - go get gopkg.in/vmihailenco/msgpack.v2
 - go get github.com/docker/libchan
 - go get github.com/docker/libchan/spdy
 - go get github.com/Sirupsen/logrus

script:
 - ./test.sh
